### ISSUE TITLE
FL log parser does not handle v3.00 format

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/emu#271]
I have some FL recordings in their usual directory structure.
EMU could not parse a file name until I placed the file in a higher level directory.

More specifically: testing with file 20221002_080000_Rec.wav:
If I place it in dataDirectory1 below, EMU works fine.
If I place it in a deeper directory ie  dataDirectory2 below, EMU does not work. It gives "string not in a correct format" error.
Yet the file in both locations passes the PowerShell Test-Path test.

$dataDirectory1 = "E:\BarmahNP_20221002\Barmah-1988Birdhide-FL09_20221002\20221002_080000_Rec.wav"
$dataDirectory2 = "E:\BarmahNP_20221002\Barmah-1988Birdhide-FL09_20221002\Barmah-1988Birdhide_20221002_Data\20221002_STUDY\20221002_080000_Rec.wav"

Here are the first few lines of the error trace.
Unhandled exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(String s)
   at Emu.Metadata.SupportFiles.FrontierLabs.LogFile.MemoryCardParser(StreamReader reader, String line) in F:\Work\GitHub\emu\src\Emu\Metadata\SupportFiles\FrontierLabs\LogFile.cs:line 206
   at Emu.Metadata.SupportFiles.FrontierLabs.LogFile.ExtractInformation() in F:\Work\GitHub\emu\src\Emu\Metadata\SupportFiles\FrontierLabs\LogFile.cs:line 498

**Comment by atruskie** [comment]
@towsey please provide sample files, ideally in a dropbox/onedrive share showing the folder structure that causeses the problem
