### ISSUE TITLE
Formatting issue when renaming files

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/emu#301]
When renaming files to change an incorrect time-zone, Frontier Lab file names that include locations with chars such as +-[], result in an error message:
Unhandled exception: System.InvalidOperationException: Could not find color or style '-38.36231+145.31787'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 22
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 77
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 117

Adding "-F compact" to the command line solved the problem.

The square brackets are removed from the output file names. 
20221010T010000+0000_REC [-38.36231+145.31787].wav => 20221010T110000+1000_REC_-38.36231+145.31787.wav

**Comment by atruskie** [comment]
ok I fixed it, patch coming soon:

![image](https://user-images.githubusercontent.com/1452968/207219191-be632644-373a-414b-8170-4e7dbd016e7c.png)
