### ISSUE TITLE
Unhandled exception: System.DivideByZeroException

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/emu#303]
### Discussed in https://github.com/QutEcoacoustics/emu/discussions/302

<div type='discussions-op-text'>

<sup>Originally posted by **DougPHynes** December 14, 2022</sup>
Hello EMU Community,

I ran EMU 6.2 on a large directory of WAV files (generated from an Wildlife Acoustics SM4BAT-FS):

`PS C:\Users\HynesD> Set-Location -Path "C:\Users\HynesD\emu\emu_6.2.0"`
`PS C:\Users\HynesD\emu\emu_6.2.0> .\emu.exe metadata --no-checksum E:\acousticData\raw\bats\\**\*.wav -F CSV -C -O C:\Users\HynesD\emu\emuOutput\bats.csv`     

It seemed to output a CSV okay, but I got the message below.
I did notice, after the fact, that included in my directory were a few seemingly corrupt files, with no discernable durations.
Maybe that caused the message, and all is actually well?

Doug Hynes 
</div>

```
Unhandled exception: System.DivideByZeroException: Attempted to divide by zero.
   at Emu.Metadata.WaveHeaderExtractor.<>c__DisplayClass5_0.<NonAsyncPart>b__0(Range d) in F:\Work\GitHub\emu\src\Emu\Metadata\WaveHeaderExtractor.cs:l
ine 81
   at Emu.Metadata.WaveHeaderExtractor.NonAsyncPart(Stream stream, Range formatChunk, Fin`1 dataChunk, Recording recording)
   at Emu.Metadata.WaveHeaderExtractor.ProcessFileAsync(TargetInformation information, Recording recording) in F:\Work\GitHub\emu\src\Emu\Metadata\Wave
HeaderExtractor.cs:line 66
   at Emu.Commands.Metadata.Metadata.InvokeAsync(InvocationContext invocationContext) in F:\Work\GitHub\emu\src\Emu\Commands\Metadata\Metadata.cs:line 
97
   at Emu.Extensions.System.CommandLine.CommandLineExtensions.<>c__DisplayClass0_0`3.<<UseEmuCommand>b__1>d.MoveNext() in F:\Work\GitHub\emu\src\Emu\Ex
tensions\System\CommandLine\CommandLineExtensions.cs:line 73
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
```

**Comment by atruskie** [comment]
@DougPHynes it'd be great if we could add the sample file that triggered the fault to our test corpus

**Comment by atruskie** [comment]
I think I fixed this but am not sure. If the latest release doesn't solve the issue, then reopen.
