### ISSUE TITLE
Error when running fix apply

### ISSUE THREAD

**Issue by DougPHynes** [QutEcoacoustics/emu#346]
I'm running various fixes on a batch of recordings that has FL010 and FL011 issues (and maybe others)...

I was able to fix files for FL010, but running:   

```
.\emu.exe emu fix apply -f FL011 "D:\Big Fish Island\Site ID 10292034 - North Side\2022-06-04__2022-06-27\SD1_B1_256GB\**"
```

Got me:

```
2023-03-17T15:34:44.2979366-03:00 [EROR] <1> Emu.Metadata.FrontierLabs.FlacCommentExtractor  Error parsing comment: Date `` can't be parsed
Unhandled exception: System.NotSupportedException: This check is not supported for FLAC files with variable size blocks. File a bug report on the emu repository.
   at Emu.Audio.Flac.<CalculateSampleCountFromFrameList>g__GetFrameNumber|27_0(Frame f) in F:\Work\GitHub\emu\src\Emu\Audio\Formats\FLAC\Flac.cs:line 236
   at Emu.Audio.Flac.CalculateSampleCountFromFrameList(IReadOnlyList`1 frames) in F:\Work\GitHub\emu\src\Emu\Audio\Formats\FLAC\Flac.cs:line 230
   at Emu.Audio.Flac.CountSamplesAsync(Stream stream) in F:\Work\GitHub\emu\src\Emu\Audio\Formats\FLAC\Flac.cs:line 85
   at Emu.Fixes.FrontierLabs.MetadataDurationBug.IsAffectedAsync(Stream stream) in F:\Work\GitHub\emu\src\Emu\Fixes\FrontierLabs\MetadataDurationBug.cs:line 77
   at Emu.Fixes.FrontierLabs.PartialFileRepair.FixDuration(String fragmentPath, DryRun dryRun, Stream stream) in F:\Work\GitHub\emu\src\Emu\Fixes\FrontierLabs\PartialFileRepair.cs:line 256
   at Emu.Fixes.FrontierLabs.PartialFileRepair.FixFile(String file, CheckResult affected, Data data, DryRun dryRun) in F:\Work\GitHub\emu\src\Emu\Fixes\FrontierLabs\PartialFileRepair.cs:line 199
   at Emu.Fixes.FrontierLabs.PartialFileRepair.ProcessFileAsync(String file, DryRun dryRun) in F:\Work\GitHub\emu\src\Emu\Fixes\FrontierLabs\PartialFileRepair.cs:line 127
   at Emu.FixApply.ApplyFixAsync(String file, DryRun dryRun, IFixOperation operation, CheckResult checkResult) in F:\Work\GitHub\emu\src\Emu\Commands\Fix\Apply\FixApply.cs:line 340
   at Emu.FixApply.ProcessFile(String file, DryRun dryRun, ICheckOperation[] operations) in F:\Work\GitHub\emu\src\Emu\Commands\Fix\Apply\FixApply.cs:line 207
   at Emu.FixApply.InvokeAsync(InvocationContext context) in F:\Work\GitHub\emu\src\Emu\Commands\Fix\Apply\FixApply.cs:line 96
   at Emu.Extensions.System.CommandLine.CommandLineExtensions.<>c__DisplayClass0_0`3.<<UseEmuCommand>b__1>d.MoveNext() in F:\Work\GitHub\emu\src\Emu\Extensions\System\CommandLine\CommandLineExtensions.cs:line 73
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Is this a bug?

**Comment by atruskie** [comment]
It, is a bug, can you please submit a sample file so I can reproduce the issue?

There are two error messages there. The interesting one is `This check is not supported for FLAC files with variable size blocks.`. As far as I know FL don't ever use variable size FLAC blocks. Which actually means these files are likely corrupt in some other manner.

**Comment by DougPHynes** [comment]
It appears that [this partial file named "data"](https://drive.google.com/file/d/1giemeSBBikqi49CUGgs582gGaG2dEQO9/view?usp=share_link) was triggering the bug.

I removed the file in the link above from my working directory, and all other partial files named data in my folders were fixed with `emu fix apply -f FL011`

**Comment by atruskie** [comment]
Thanks @DougPHynes  I'll look into this ASAP
