### ISSUE TITLE
Error when doing a rename

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/emu#348]
It seems we're leaving a file handle open somewhere:

```powershell
> dotnet run -- rename --template "{StartDate}{Extension}" --scan-metadata F:\Pedro\20230328\Card1\recup_dir.1\*.wav
Looking for targets...
Unhandled exception: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at Emu.Commands.Rename.Rename.<>c__DisplayClass53_0.<ApplyRename>g__Rename|2() in F:\Work\Github\emu\src\Emu\Commands\Rename\Rename.cs:line 289
   at Emu.Utilities.DryRun.WouldDo(String message, Action callback, Action dryCallback) in F:\Work\Github\emu\src\Emu\Utilities\DryRun.cs:line 83
   at Emu.Commands.Rename.Rename.ApplyRename(RenameResult rename, DryRun dryRun) in F:\Work\Github\emu\src\Emu\Commands\Rename\Rename.cs:line 275
   at Emu.Commands.Rename.Rename.ProcessFiles(IEnumerable`1 files, DryRun dryRun) in F:\Work\Github\emu\src\Emu\Commands\Rename\Rename.cs:line 165
   at Emu.Commands.Rename.Rename.InvokeAsync(InvocationContext context) in F:\Work\Github\emu\src\Emu\Commands\Rename\Rename.cs:line 105
   at Emu.Extensions.System.CommandLine.CommandLineExtensions.<>c__DisplayClass0_0`3.<<UseEmuCommand>b__1>d.MoveNext() in F:\Work\Github\emu\src\Emu\Extensions\System\CommandLine\CommandLineExtensions.cs:line 73
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I've checked and no other processes had locked the file.

**Comment by atruskie** [comment]
Available in the [7.0.0 release](https://github.com/QutEcoacoustics/emu/releases/tag/7.0.0).
